twitter:
  consumer_key: 24Wv4ne3kb8vCRwwLaEA
  consumer_secret: vDH2jUrHAFbSl6aOPtqXJHw4BVG1tYgwsNFYzHFgU
  user_token: 566735276-0uqJDEFmsaqTlFHTTvVvXbMA5fGhJNj3NLkEfwoS
  user_secret: 5ZnbNm7GhLdvdr7AJkXlXh85N5EHYUbBaD6zw7hY
facebook:
  appId: 146092035521575
  secret: ae42b649cdd66ecd532b2201e7200d44
  userId: 630541751
   
