<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class matiltimodeloBundleEntityScdUsuarioProxy extends \matilti\modeloBundle\Entity\ScdUsuario implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setUsername($username)
    {
        $this->__load();
        return parent::setUsername($username);
    }

    public function getUsername()
    {
        $this->__load();
        return parent::getUsername();
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function setCorreousuario($correousuario)
    {
        $this->__load();
        return parent::setCorreousuario($correousuario);
    }

    public function getCorreousuario()
    {
        $this->__load();
        return parent::getCorreousuario();
    }

    public function setDetalleusuario($detalleusuario)
    {
        $this->__load();
        return parent::setDetalleusuario($detalleusuario);
    }

    public function getDetalleusuario()
    {
        $this->__load();
        return parent::getDetalleusuario();
    }

    public function setUltimavisitausuario($ultimavisitausuario)
    {
        $this->__load();
        return parent::setUltimavisitausuario($ultimavisitausuario);
    }

    public function getUltimavisitausuario()
    {
        $this->__load();
        return parent::getUltimavisitausuario();
    }

    public function setIpusuario($ipusuario)
    {
        $this->__load();
        return parent::setIpusuario($ipusuario);
    }

    public function getIpusuario()
    {
        $this->__load();
        return parent::getIpusuario();
    }

    public function setSalt($salt)
    {
        $this->__load();
        return parent::setSalt($salt);
    }

    public function getSalt()
    {
        $this->__load();
        return parent::getSalt();
    }

    public function setNombreusuario($nombreusuario)
    {
        $this->__load();
        return parent::setNombreusuario($nombreusuario);
    }

    public function getNombreusuario()
    {
        $this->__load();
        return parent::getNombreusuario();
    }

    public function setApellidousuario($apellidousuario)
    {
        $this->__load();
        return parent::setApellidousuario($apellidousuario);
    }

    public function getApellidousuario()
    {
        $this->__load();
        return parent::getApellidousuario();
    }

    public function setTelefonousuario($telefonousuario)
    {
        $this->__load();
        return parent::setTelefonousuario($telefonousuario);
    }

    public function getTelefonousuario()
    {
        $this->__load();
        return parent::getTelefonousuario();
    }

    public function setNacimientousuario($nacimientousuario)
    {
        $this->__load();
        return parent::setNacimientousuario($nacimientousuario);
    }

    public function getNacimientousuario()
    {
        $this->__load();
        return parent::getNacimientousuario();
    }

    public function setLatusuario($latusuario)
    {
        $this->__load();
        return parent::setLatusuario($latusuario);
    }

    public function getLatusuario()
    {
        $this->__load();
        return parent::getLatusuario();
    }

    public function setLonusuario($lonusuario)
    {
        $this->__load();
        return parent::setLonusuario($lonusuario);
    }

    public function getLonusuario()
    {
        $this->__load();
        return parent::getLonusuario();
    }

    public function setDireccionusuario($direccionusuario)
    {
        $this->__load();
        return parent::setDireccionusuario($direccionusuario);
    }

    public function getDireccionusuario()
    {
        $this->__load();
        return parent::getDireccionusuario();
    }

    public function setSexousuario($sexousuario)
    {
        $this->__load();
        return parent::setSexousuario($sexousuario);
    }

    public function getSexousuario()
    {
        $this->__load();
        return parent::getSexousuario();
    }

    public function setRegistrousuario($registrousuario)
    {
        $this->__load();
        return parent::setRegistrousuario($registrousuario);
    }

    public function getRegistrousuario()
    {
        $this->__load();
        return parent::getRegistrousuario();
    }

    public function setCuentausuario($cuentausuario)
    {
        $this->__load();
        return parent::setCuentausuario($cuentausuario);
    }

    public function getCuentausuario()
    {
        $this->__load();
        return parent::getCuentausuario();
    }

    public function setImagenusuario($imagenusuario)
    {
        $this->__load();
        return parent::setImagenusuario($imagenusuario);
    }

    public function getImagenusuario()
    {
        $this->__load();
        return parent::getImagenusuario();
    }

    public function setEstado(\matilti\modeloBundle\Entity\ScdEstado $estado)
    {
        $this->__load();
        return parent::setEstado($estado);
    }

    public function getEstado()
    {
        $this->__load();
        return parent::getEstado();
    }

    public function setLocalidad(\matilti\modeloBundle\Entity\ScdLocalidad $localidad)
    {
        $this->__load();
        return parent::setLocalidad($localidad);
    }

    public function getLocalidad()
    {
        $this->__load();
        return parent::getLocalidad();
    }

    public function addScdRol(\matilti\modeloBundle\Entity\ScdRol $rol)
    {
        $this->__load();
        return parent::addScdRol($rol);
    }

    public function getRol()
    {
        $this->__load();
        return parent::getRol();
    }

    public function eraseCredentials()
    {
        $this->__load();
        return parent::eraseCredentials();
    }

    public function getRoles()
    {
        $this->__load();
        return parent::getRoles();
    }

    public function equals(\Symfony\Component\Security\Core\User\UserInterface $user)
    {
        $this->__load();
        return parent::equals($user);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getUserRoles()
    {
        $this->__load();
        return parent::getUserRoles();
    }

    public function serialize()
    {
        $this->__load();
        return parent::serialize();
    }

    public function unserialize($data)
    {
        $this->__load();
        return parent::unserialize($data);
    }

    public function addScdEntidad(\matilti\modeloBundle\Entity\ScdEntidad $entidad)
    {
        $this->__load();
        return parent::addScdEntidad($entidad);
    }

    public function getEntidad()
    {
        $this->__load();
        return parent::getEntidad();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'username', 'password', 'correousuario', 'detalleusuario', 'ultimavisitausuario', 'ipusuario', 'salt', 'nombreusuario', 'apellidousuario', 'telefonousuario', 'nacimientousuario', 'latusuario', 'lonusuario', 'direccionusuario', 'sexousuario', 'registrousuario', 'cuentausuario', 'imagenusuario', 'estado', 'localidad', 'rol', 'entidad');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}