security:
    encoders:
        matilti\modeloBundle\Entity\ScdUsuario:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    providers:
        main:
            entity: { class: matilti\modeloBundle\Entity\ScdUsuario, property: username }

    firewalls:
        main:
            pattern:    ^/
            anonymous: ~
 #           http_basic:
            form_login:
                check_path: /login_check
                login_path: /login
                default_target_path: /home
                always_use_default_target_path: true
            logout: true
            security: true
            anonymous: true

    access_control:
        - { path: ^/login*, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }
        - { path: ^/reporteria, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/home/.*, role: IS_AUTHENTICATED_ANONIMOUSLY }
#        - { path: ^/.*, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/mensajeria, roles: ROLE_CONTENT_MANAGEMENT, requires_channel: http}
#        - { path: ^/admin*, roles: [ROLE_MAINTENANCE], requires_channel: http }
#        - { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
