matilti\modeloBundle\Entity\ScdEntidad:
  type: entity
  table: scd_entidad
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    nombreentidad:
      type: string
      length: 75
      fixed: false
      nullable: false
    correoentidad:
      type: string
      length: null
      fixed: false
      nullable: true
    telefonoentidad:
      type: string
      length: 25
      fixed: false
      nullable: true
    urlentidad:
      type: string
      length: null
      fixed: false
      nullable: true
    xmlentidad:
      type: text
      nullable: true
    latentidad:
      type: float
      nullable: false
    lonentidad:
      type: float
      nullable: false
  manyToMany:
    usuario:
      targetEntity: ScdUsuario
      cascade: {  }
      mappedBy: entidad
      inversedBy: null
      joinTable: null
      orderBy: null
  oneToOne:
    localidad:
      targetEntity: ScdLocalidad
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        localidad_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
