matilti\modeloBundle\Entity\ScdHistorialOperacion:
  type: entity
  table: scd_historial_operacion
  repositoryClass: matilti\modeloBundle\Repository\ScdHistorialOperacionRepository
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: SEQUENCE
    fechahisoperacion:
      type: datetime
      nullable: false
    detallehisoperacion:
      type: string
      length: 250
      fixed: false
      nullable: false
    ipoperacion:
      type: string
      length: null
      fixed: false
      nullable: false
  oneToOne:
    usuario:
      targetEntity: ScdUsuario
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        usuario_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
