<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class matiltimodeloBundleEntityScdLocalidadProxy extends \matilti\modeloBundle\Entity\ScdLocalidad implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setNombrelocalidad($nombrelocalidad)
    {
        $this->__load();
        return parent::setNombrelocalidad($nombrelocalidad);
    }

    public function getNombrelocalidad()
    {
        $this->__load();
        return parent::getNombrelocalidad();
    }

    public function setLatlocalidad($latlocalidad)
    {
        $this->__load();
        return parent::setLatlocalidad($latlocalidad);
    }

    public function getLatlocalidad()
    {
        $this->__load();
        return parent::getLatlocalidad();
    }

    public function setLoglocalidad($loglocalidad)
    {
        $this->__load();
        return parent::setLoglocalidad($loglocalidad);
    }

    public function getLoglocalidad()
    {
        $this->__load();
        return parent::getLoglocalidad();
    }

    public function setDescripcionlocalidad($descripcionlocalidad)
    {
        $this->__load();
        return parent::setDescripcionlocalidad($descripcionlocalidad);
    }

    public function getDescripcionlocalidad()
    {
        $this->__load();
        return parent::getDescripcionlocalidad();
    }

    public function setPoblacionlocalidad($poblacionlocalidad)
    {
        $this->__load();
        return parent::setPoblacionlocalidad($poblacionlocalidad);
    }

    public function getPoblacionlocalidad()
    {
        $this->__load();
        return parent::getPoblacionlocalidad();
    }

    public function setLocalidad(\matilti\modeloBundle\Entity\ScdLocalidad $localidad)
    {
        $this->__load();
        return parent::setLocalidad($localidad);
    }

    public function getLocalidad()
    {
        $this->__load();
        return parent::getLocalidad();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombrelocalidad', 'latlocalidad', 'loglocalidad', 'descripcionlocalidad', 'poblacionlocalidad', 'localidad');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}