<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class matiltimodeloBundleEntityScdEncuestaProxy extends \matilti\modeloBundle\Entity\ScdEncuesta implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setMensajeencuesta($mensajeencuesta)
    {
        $this->__load();
        return parent::setMensajeencuesta($mensajeencuesta);
    }

    public function getMensajeencuesta()
    {
        $this->__load();
        return parent::getMensajeencuesta();
    }

    public function setRespuestasencuesta($respuestasencuesta)
    {
        $this->__load();
        return parent::setRespuestasencuesta($respuestasencuesta);
    }

    public function getRespuestasencuesta()
    {
        $this->__load();
        return parent::getRespuestasencuesta();
    }

    public function setFechahorainicio($fechahorainicio)
    {
        $this->__load();
        return parent::setFechahorainicio($fechahorainicio);
    }

    public function getFechahorainicio()
    {
        $this->__load();
        return parent::getFechahorainicio();
    }

    public function setFechahorafin($fechahorafin)
    {
        $this->__load();
        return parent::setFechahorafin($fechahorafin);
    }

    public function getFechahorafin()
    {
        $this->__load();
        return parent::getFechahorafin();
    }

    public function setEncuestaactiva($encuestaactiva)
    {
        $this->__load();
        return parent::setEncuestaactiva($encuestaactiva);
    }

    public function getEncuestaactiva()
    {
        $this->__load();
        return parent::getEncuestaactiva();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'mensajeencuesta', 'respuestasencuesta', 'fechahorainicio', 'fechahorafin', 'encuestaactiva');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}