<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class matiltimodeloBundleEntityOutboxProxy extends \matilti\modeloBundle\Entity\Outbox implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setUpdatedindb($updatedindb)
    {
        $this->__load();
        return parent::setUpdatedindb($updatedindb);
    }

    public function getUpdatedindb()
    {
        $this->__load();
        return parent::getUpdatedindb();
    }

    public function setInsertintodb($insertintodb)
    {
        $this->__load();
        return parent::setInsertintodb($insertintodb);
    }

    public function getInsertintodb()
    {
        $this->__load();
        return parent::getInsertintodb();
    }

    public function setSendingdatetime($sendingdatetime)
    {
        $this->__load();
        return parent::setSendingdatetime($sendingdatetime);
    }

    public function getSendingdatetime()
    {
        $this->__load();
        return parent::getSendingdatetime();
    }

    public function setText($text)
    {
        $this->__load();
        return parent::setText($text);
    }

    public function getText()
    {
        $this->__load();
        return parent::getText();
    }

    public function setDestinationnumber($destinationnumber)
    {
        $this->__load();
        return parent::setDestinationnumber($destinationnumber);
    }

    public function getDestinationnumber()
    {
        $this->__load();
        return parent::getDestinationnumber();
    }

    public function setCoding($coding)
    {
        $this->__load();
        return parent::setCoding($coding);
    }

    public function getCoding()
    {
        $this->__load();
        return parent::getCoding();
    }

    public function setUdh($udh)
    {
        $this->__load();
        return parent::setUdh($udh);
    }

    public function getUdh()
    {
        $this->__load();
        return parent::getUdh();
    }

    public function setClass($class)
    {
        $this->__load();
        return parent::setClass($class);
    }

    public function getClass()
    {
        $this->__load();
        return parent::getClass();
    }

    public function setTextdecoded($textdecoded)
    {
        $this->__load();
        return parent::setTextdecoded($textdecoded);
    }

    public function getTextdecoded()
    {
        $this->__load();
        return parent::getTextdecoded();
    }

    public function setMultipart($multipart)
    {
        $this->__load();
        return parent::setMultipart($multipart);
    }

    public function getMultipart()
    {
        $this->__load();
        return parent::getMultipart();
    }

    public function setRelativevalidity($relativevalidity)
    {
        $this->__load();
        return parent::setRelativevalidity($relativevalidity);
    }

    public function getRelativevalidity()
    {
        $this->__load();
        return parent::getRelativevalidity();
    }

    public function setSenderid($senderid)
    {
        $this->__load();
        return parent::setSenderid($senderid);
    }

    public function getSenderid()
    {
        $this->__load();
        return parent::getSenderid();
    }

    public function setSendingtimeout($sendingtimeout)
    {
        $this->__load();
        return parent::setSendingtimeout($sendingtimeout);
    }

    public function getSendingtimeout()
    {
        $this->__load();
        return parent::getSendingtimeout();
    }

    public function setDeliveryreport($deliveryreport)
    {
        $this->__load();
        return parent::setDeliveryreport($deliveryreport);
    }

    public function getDeliveryreport()
    {
        $this->__load();
        return parent::getDeliveryreport();
    }

    public function setCreatorid($creatorid)
    {
        $this->__load();
        return parent::setCreatorid($creatorid);
    }

    public function getCreatorid()
    {
        $this->__load();
        return parent::getCreatorid();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'updatedindb', 'insertintodb', 'sendingdatetime', 'text', 'destinationnumber', 'coding', 'udh', 'class', 'textdecoded', 'multipart', 'relativevalidity', 'senderid', 'sendingtimeout', 'deliveryreport', 'creatorid');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}