<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class matiltimodeloBundleEntityScdRolProxy extends \matilti\modeloBundle\Entity\ScdRol implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setNombrerol($nombrerol)
    {
        $this->__load();
        return parent::setNombrerol($nombrerol);
    }

    public function getNombrerol()
    {
        $this->__load();
        return parent::getNombrerol();
    }

    public function setDetallerol($detallerol)
    {
        $this->__load();
        return parent::setDetallerol($detallerol);
    }

    public function getDetallerol()
    {
        $this->__load();
        return parent::getDetallerol();
    }

    public function addScdReglaSms(\matilti\modeloBundle\Entity\ScdReglaSms $regla)
    {
        $this->__load();
        return parent::addScdReglaSms($regla);
    }

    public function getRegla()
    {
        $this->__load();
        return parent::getRegla();
    }

    public function addScdUsuario(\matilti\modeloBundle\Entity\ScdUsuario $usuario)
    {
        $this->__load();
        return parent::addScdUsuario($usuario);
    }

    public function getUsuario()
    {
        $this->__load();
        return parent::getUsuario();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getRole()
    {
        $this->__load();
        return parent::getRole();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombrerol', 'detallerol', 'usuario', 'regla');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}