<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class matiltimodeloBundleEntityScdEntidadProxy extends \matilti\modeloBundle\Entity\ScdEntidad implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setNombreentidad($nombreentidad)
    {
        $this->__load();
        return parent::setNombreentidad($nombreentidad);
    }

    public function getNombreentidad()
    {
        $this->__load();
        return parent::getNombreentidad();
    }

    public function setCorreoentidad($correoentidad)
    {
        $this->__load();
        return parent::setCorreoentidad($correoentidad);
    }

    public function getCorreoentidad()
    {
        $this->__load();
        return parent::getCorreoentidad();
    }

    public function setTelefonoentidad($telefonoentidad)
    {
        $this->__load();
        return parent::setTelefonoentidad($telefonoentidad);
    }

    public function getTelefonoentidad()
    {
        $this->__load();
        return parent::getTelefonoentidad();
    }

    public function setUrlentidad($urlentidad)
    {
        $this->__load();
        return parent::setUrlentidad($urlentidad);
    }

    public function getUrlentidad()
    {
        $this->__load();
        return parent::getUrlentidad();
    }

    public function setXmlentidad($xmlentidad)
    {
        $this->__load();
        return parent::setXmlentidad($xmlentidad);
    }

    public function getXmlentidad()
    {
        $this->__load();
        return parent::getXmlentidad();
    }

    public function setLatentidad($latentidad)
    {
        $this->__load();
        return parent::setLatentidad($latentidad);
    }

    public function getLatentidad()
    {
        $this->__load();
        return parent::getLatentidad();
    }

    public function setLonentidad($lonentidad)
    {
        $this->__load();
        return parent::setLonentidad($lonentidad);
    }

    public function getLonentidad()
    {
        $this->__load();
        return parent::getLonentidad();
    }

    public function setLocalidad(\matilti\modeloBundle\Entity\ScdLocalidad $localidad)
    {
        $this->__load();
        return parent::setLocalidad($localidad);
    }

    public function getLocalidad()
    {
        $this->__load();
        return parent::getLocalidad();
    }

    public function addScdUsuario(\matilti\modeloBundle\Entity\ScdUsuario $usuario)
    {
        $this->__load();
        return parent::addScdUsuario($usuario);
    }

    public function getUsuario()
    {
        $this->__load();
        return parent::getUsuario();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombreentidad', 'correoentidad', 'telefonoentidad', 'urlentidad', 'xmlentidad', 'latentidad', 'lonentidad', 'localidad', 'usuario');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}