<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class matiltimodeloBundleEntityScdEnviadoProxy extends \matilti\modeloBundle\Entity\ScdEnviado implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setMensajeenviado($mensajeenviado)
    {
        $this->__load();
        return parent::setMensajeenviado($mensajeenviado);
    }

    public function getMensajeenviado()
    {
        $this->__load();
        return parent::getMensajeenviado();
    }

    public function setFechahoraenviado($fechahoraenviado)
    {
        $this->__load();
        return parent::setFechahoraenviado($fechahoraenviado);
    }

    public function getFechahoraenviado()
    {
        $this->__load();
        return parent::getFechahoraenviado();
    }

    public function setEncuesta(\matilti\modeloBundle\Entity\ScdEncuesta $encuesta)
    {
        $this->__load();
        return parent::setEncuesta($encuesta);
    }

    public function getEncuesta()
    {
        $this->__load();
        return parent::getEncuesta();
    }

    public function setRespuesta(\matilti\modeloBundle\Entity\ScdRecibido $respuesta)
    {
        $this->__load();
        return parent::setRespuesta($respuesta);
    }

    public function getRespuesta()
    {
        $this->__load();
        return parent::getRespuesta();
    }

    public function setUsuario(\matilti\modeloBundle\Entity\ScdUsuario $usuario)
    {
        $this->__load();
        return parent::setUsuario($usuario);
    }

    public function getUsuario()
    {
        $this->__load();
        return parent::getUsuario();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'mensajeenviado', 'fechahoraenviado', 'encuesta', 'respuesta', 'usuario');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}