<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class matiltimodeloBundleEntityScdRecibidoProxy extends \matilti\modeloBundle\Entity\ScdRecibido implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setMensajerecibido($mensajerecibido)
    {
        $this->__load();
        return parent::setMensajerecibido($mensajerecibido);
    }

    public function getMensajerecibido()
    {
        $this->__load();
        return parent::getMensajerecibido();
    }

    public function setFecharecibido($fecharecibido)
    {
        $this->__load();
        return parent::setFecharecibido($fecharecibido);
    }

    public function getFecharecibido()
    {
        $this->__load();
        return parent::getFecharecibido();
    }

    public function setReglaId($reglaId)
    {
        $this->__load();
        return parent::setReglaId($reglaId);
    }

    public function getReglaId()
    {
        $this->__load();
        return parent::getReglaId();
    }

    public function setUsuario(\matilti\modeloBundle\Entity\ScdUsuario $usuario)
    {
        $this->__load();
        return parent::setUsuario($usuario);
    }

    public function getUsuario()
    {
        $this->__load();
        return parent::getUsuario();
    }

    public function setFechahorarecibido($fechahorarecibido)
    {
        $this->__load();
        return parent::setFechahorarecibido($fechahorarecibido);
    }

    public function getFechahorarecibido()
    {
        $this->__load();
        return parent::getFechahorarecibido();
    }

    public function setRegla(\matilti\modeloBundle\Entity\ScdReglaSms $regla)
    {
        $this->__load();
        return parent::setRegla($regla);
    }

    public function getRegla()
    {
        $this->__load();
        return parent::getRegla();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'mensajerecibido', 'fechahorarecibido', 'regla', 'usuario');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}