<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class matiltimodeloBundleEntityOutboxMultipartProxy extends \matilti\modeloBundle\Entity\OutboxMultipart implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setSequenceposition($sequenceposition)
    {
        $this->__load();
        return parent::setSequenceposition($sequenceposition);
    }

    public function getSequenceposition()
    {
        $this->__load();
        return parent::getSequenceposition();
    }

    public function setText($text)
    {
        $this->__load();
        return parent::setText($text);
    }

    public function getText()
    {
        $this->__load();
        return parent::getText();
    }

    public function setCoding($coding)
    {
        $this->__load();
        return parent::setCoding($coding);
    }

    public function getCoding()
    {
        $this->__load();
        return parent::getCoding();
    }

    public function setUdh($udh)
    {
        $this->__load();
        return parent::setUdh($udh);
    }

    public function getUdh()
    {
        $this->__load();
        return parent::getUdh();
    }

    public function setClass($class)
    {
        $this->__load();
        return parent::setClass($class);
    }

    public function getClass()
    {
        $this->__load();
        return parent::getClass();
    }

    public function setTextdecoded($textdecoded)
    {
        $this->__load();
        return parent::setTextdecoded($textdecoded);
    }

    public function getTextdecoded()
    {
        $this->__load();
        return parent::getTextdecoded();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'sequenceposition', 'text', 'coding', 'udh', 'class', 'textdecoded');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}