<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class matiltimodeloBundleEntityScdDenunciaProxy extends \matilti\modeloBundle\Entity\ScdDenuncia implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setMensajedenuncia($mensajedenuncia)
    {
        $this->__load();
        return parent::setMensajedenuncia($mensajedenuncia);
    }

    public function getMensajedenuncia()
    {
        $this->__load();
        return parent::getMensajedenuncia();
    }

    public function setFechahorainicio($fechahorainicio)
    {
        $this->__load();
        return parent::setFechahorainicio($fechahorainicio);
    }

    public function getFechahorainicio()
    {
        $this->__load();
        return parent::getFechahorainicio();
    }

    public function setFechahorafin($fechahorafin)
    {
        $this->__load();
        return parent::setFechahorafin($fechahorafin);
    }

    public function getFechahorafin()
    {
        $this->__load();
        return parent::getFechahorafin();
    }

    public function setDenunciaactiva($denunciaactiva)
    {
        $this->__load();
        return parent::setDenunciaactiva($denunciaactiva);
    }

    public function getDenunciaactiva()
    {
        $this->__load();
        return parent::getDenunciaactiva();
    }

    public function setDenuncia(\matilti\modeloBundle\Entity\ScdDenuncia $denuncia)
    {
        $this->__load();
        return parent::setDenuncia($denuncia);
    }

    public function getDenuncia()
    {
        $this->__load();
        return parent::getDenuncia();
    }

    public function setUsuario(\matilti\modeloBundle\Entity\ScdUsuario $usuario)
    {
        $this->__load();
        return parent::setUsuario($usuario);
    }

    public function getUsuario()
    {
        $this->__load();
        return parent::getUsuario();
    }

    public function setEntidad(\matilti\modeloBundle\Entity\ScdEntidad $entidad)
    {
        $this->__load();
        return parent::setEntidad($entidad);
    }

    public function getEntidad()
    {
        $this->__load();
        return parent::getEntidad();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'mensajedenuncia', 'fechahorainicio', 'fechahorafin', 'denunciaactiva', 'denuncia', 'usuario', 'entidad');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}