<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class matiltimodeloBundleEntitySentitemsProxy extends \matilti\modeloBundle\Entity\Sentitems implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setSequenceposition($sequenceposition)
    {
        $this->__load();
        return parent::setSequenceposition($sequenceposition);
    }

    public function getSequenceposition()
    {
        $this->__load();
        return parent::getSequenceposition();
    }

    public function setUpdatedindb($updatedindb)
    {
        $this->__load();
        return parent::setUpdatedindb($updatedindb);
    }

    public function getUpdatedindb()
    {
        $this->__load();
        return parent::getUpdatedindb();
    }

    public function setInsertintodb($insertintodb)
    {
        $this->__load();
        return parent::setInsertintodb($insertintodb);
    }

    public function getInsertintodb()
    {
        $this->__load();
        return parent::getInsertintodb();
    }

    public function setSendingdatetime($sendingdatetime)
    {
        $this->__load();
        return parent::setSendingdatetime($sendingdatetime);
    }

    public function getSendingdatetime()
    {
        $this->__load();
        return parent::getSendingdatetime();
    }

    public function setDeliverydatetime($deliverydatetime)
    {
        $this->__load();
        return parent::setDeliverydatetime($deliverydatetime);
    }

    public function getDeliverydatetime()
    {
        $this->__load();
        return parent::getDeliverydatetime();
    }

    public function setText($text)
    {
        $this->__load();
        return parent::setText($text);
    }

    public function getText()
    {
        $this->__load();
        return parent::getText();
    }

    public function setDestinationnumber($destinationnumber)
    {
        $this->__load();
        return parent::setDestinationnumber($destinationnumber);
    }

    public function getDestinationnumber()
    {
        $this->__load();
        return parent::getDestinationnumber();
    }

    public function setCoding($coding)
    {
        $this->__load();
        return parent::setCoding($coding);
    }

    public function getCoding()
    {
        $this->__load();
        return parent::getCoding();
    }

    public function setUdh($udh)
    {
        $this->__load();
        return parent::setUdh($udh);
    }

    public function getUdh()
    {
        $this->__load();
        return parent::getUdh();
    }

    public function setSmscnumber($smscnumber)
    {
        $this->__load();
        return parent::setSmscnumber($smscnumber);
    }

    public function getSmscnumber()
    {
        $this->__load();
        return parent::getSmscnumber();
    }

    public function setClass($class)
    {
        $this->__load();
        return parent::setClass($class);
    }

    public function getClass()
    {
        $this->__load();
        return parent::getClass();
    }

    public function setTextdecoded($textdecoded)
    {
        $this->__load();
        return parent::setTextdecoded($textdecoded);
    }

    public function getTextdecoded()
    {
        $this->__load();
        return parent::getTextdecoded();
    }

    public function setSenderid($senderid)
    {
        $this->__load();
        return parent::setSenderid($senderid);
    }

    public function getSenderid()
    {
        $this->__load();
        return parent::getSenderid();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setStatuserror($statuserror)
    {
        $this->__load();
        return parent::setStatuserror($statuserror);
    }

    public function getStatuserror()
    {
        $this->__load();
        return parent::getStatuserror();
    }

    public function setTpmr($tpmr)
    {
        $this->__load();
        return parent::setTpmr($tpmr);
    }

    public function getTpmr()
    {
        $this->__load();
        return parent::getTpmr();
    }

    public function setRelativevalidity($relativevalidity)
    {
        $this->__load();
        return parent::setRelativevalidity($relativevalidity);
    }

    public function getRelativevalidity()
    {
        $this->__load();
        return parent::getRelativevalidity();
    }

    public function setCreatorid($creatorid)
    {
        $this->__load();
        return parent::setCreatorid($creatorid);
    }

    public function getCreatorid()
    {
        $this->__load();
        return parent::getCreatorid();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'sequenceposition', 'updatedindb', 'insertintodb', 'sendingdatetime', 'deliverydatetime', 'text', 'destinationnumber', 'coding', 'udh', 'smscnumber', 'class', 'textdecoded', 'senderid', 'status', 'statuserror', 'tpmr', 'relativevalidity', 'creatorid');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}