<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class matiltimodeloBundleEntityScdAccionProxy extends \matilti\modeloBundle\Entity\ScdAccion implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setTituloaccion($tituloaccion)
    {
        $this->__load();
        return parent::setTituloaccion($tituloaccion);
    }

    public function getTituloaccion()
    {
        $this->__load();
        return parent::getTituloaccion();
    }

    public function setUriaccion($uriaccion)
    {
        $this->__load();
        return parent::setUriaccion($uriaccion);
    }

    public function getUriaccion()
    {
        $this->__load();
        return parent::getUriaccion();
    }

    public function setDetalleaccion($detalleaccion)
    {
        $this->__load();
        return parent::setDetalleaccion($detalleaccion);
    }

    public function getDetalleaccion()
    {
        $this->__load();
        return parent::getDetalleaccion();
    }

    public function setNamespacetitulo($namespacetitulo)
    {
        $this->__load();
        return parent::setNamespacetitulo($namespacetitulo);
    }

    public function getNamespacetitulo()
    {
        $this->__load();
        return parent::getNamespacetitulo();
    }

    public function setRol(\matilti\modeloBundle\Entity\ScdRol $rol)
    {
        $this->__load();
        return parent::setRol($rol);
    }

    public function getRol()
    {
        $this->__load();
        return parent::getRol();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'tituloaccion', 'uriaccion', 'detalleaccion', 'namespacetitulo', 'rol');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}